# Generated by Django 3.1.14 on 2022-01-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20220124_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='tiny-desicion-logo.png', null=True, upload_to=''),
        ),
    ]
