# Generated by Django 3.1.14 on 2022-01-26 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_project_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(default='tiny-desicion-logo.png', null=True, upload_to=''),
        ),
    ]
