# Generated by Django 3.1.14 on 2022-01-26 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20220126_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='tiny-desicion-logo.png', null=True, upload_to=''),
        ),
    ]
